---
name: "authorizeddecryptagon"

services:
  app:
    build: .
    ports:
      - "8011:3000"
    networks:
      - authorizeddecryptagon_net
    depends_on:
      - db

  db:
    image: mongo:4.4.18
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js
    networks:
      - authorizeddecryptagon_net

networks:
  authorizeddecryptagon_net:
